/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_api_entries_get"];
        put?: never;
        /** Create Entry */
        post: operations["create_entry_api_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChainState */
        ChainState: {
            /** Ok */
            ok: boolean;
            /** Count */
            count: number;
            /** Broken At */
            broken_at?: number | null;
        };
        /** EntriesOut */
        EntriesOut: {
            /** Entries */
            entries: components["schemas"]["EntryOut"][];
            chain: components["schemas"]["ChainState"];
        };
        /** EntryIn */
        EntryIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "guided" | "free";
            /**
             * Feeling
             * @default
             */
            feeling: string;
            /**
             * Why
             * @default
             */
            why: string;
            /**
             * Cause
             * @default
             */
            cause: string;
            /**
             * Helps
             * @default
             */
            helps: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** Privacy Choice */
            privacy_choice?: ("keep" | "blur") | null;
        };
        /** EntryOut */
        EntryOut: {
            /** Id */
            id: string;
            /** At */
            at: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "guided" | "free";
            /**
             * Feeling
             * @default
             */
            feeling: string;
            /**
             * Why
             * @default
             */
            why: string;
            /**
             * Cause
             * @default
             */
            cause: string;
            /**
             * Helps
             * @default
             */
            helps: string;
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Blurred
             * @default false
             */
            blurred: boolean;
            /**
             * Src
             * @default self
             */
            src: string;
            /**
             * Tier
             * @default stated
             */
            tier: string;
            /**
             * Ttl
             * @default permanent
             */
            ttl: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Ok */
            ok: boolean;
            chain: components["schemas"]["ChainState"];
        };
        /** SaveOut */
        SaveOut: {
            /** Saved */
            saved: boolean;
            /**
             * Needs Choice
             * @default false
             */
            needs_choice: boolean;
            /**
             * Found
             * @default []
             */
            found: string[];
            entry?: components["schemas"]["EntryOut"] | null;
            chain?: components["schemas"]["ChainState"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_entries_api_entries_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_api_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
