/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_api_entries_get"];
        put?: never;
        /** Create Entry */
        post: operations["create_entry_api_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Personas */
        get: operations["list_personas_api_personas_get"];
        put?: never;
        /** Create Persona */
        post: operations["create_persona_api_personas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personas/{persona_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Persona */
        put: operations["update_persona_api_personas__persona_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personas/{persona_id}/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Thread */
        get: operations["read_thread_api_personas__persona_id__thread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/truths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Truths */
        get: operations["list_truths_api_truths_get"];
        put?: never;
        /** Create Truth */
        post: operations["create_truth_api_truths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loose-ends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Loose Ends */
        get: operations["list_loose_ends_api_loose_ends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loose-ends/{loose_end_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Loose End */
        post: operations["answer_loose_end_api_loose_ends__loose_end_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Text */
        post: operations["import_text_api_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/you": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** You */
        get: operations["you_api_you_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reflection/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reflection Settings */
        get: operations["reflection_settings_api_reflection_settings_get"];
        /** Set Reflection Settings */
        put: operations["set_reflection_settings_api_reflection_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reflection/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Related To Draft
         * @description Past entries close to something still being written.
         *
         *     The draft is embedded and thrown away. Nothing is stored, nothing is
         *     written to any stream, and the draft never becomes a record by being looked
         *     at: only pressing Keep does that.
         */
        post: operations["related_to_draft_api_reflection_related_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reflection/related/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Related Entries
         * @description Past entries close to this one. Pull-based: nothing calls this uninvited.
         */
        get: operations["related_entries_api_reflection_related__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Everything
         * @description The one door out. ADR 002's role-swap is applied here and nowhere else.
         */
        get: operations["export_everything_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Demo */
        post: operations["load_demo_api_demo_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/wipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wipe Demo */
        post: operations["wipe_demo_api_demo_wipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChainState */
        ChainState: {
            /** Ok */
            ok: boolean;
            /** Count */
            count: number;
            /** Broken At */
            broken_at?: number | null;
        };
        /** EntriesOut */
        EntriesOut: {
            /** Entries */
            entries: components["schemas"]["EntryOut"][];
            chain: components["schemas"]["ChainState"];
        };
        /** EntryIn */
        EntryIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "guided" | "free";
            /**
             * Feeling
             * @default
             */
            feeling: string;
            /**
             * Why
             * @default
             */
            why: string;
            /**
             * Cause
             * @default
             */
            cause: string;
            /**
             * Helps
             * @default
             */
            helps: string;
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Persona Ids
             * @default []
             */
            persona_ids: string[];
            /** Privacy Choice */
            privacy_choice?: ("keep" | "blur") | null;
        };
        /** EntryOut */
        EntryOut: {
            /** Id */
            id: string;
            /** At */
            at: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "guided" | "free";
            /**
             * Feeling
             * @default
             */
            feeling: string;
            /**
             * Why
             * @default
             */
            why: string;
            /**
             * Cause
             * @default
             */
            cause: string;
            /**
             * Helps
             * @default
             */
            helps: string;
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Blurred
             * @default false
             */
            blurred: boolean;
            /**
             * Persona Ids
             * @default []
             */
            persona_ids: string[];
            /**
             * Demo
             * @default false
             */
            demo: boolean;
            /**
             * Src
             * @default self
             */
            src: string;
            /**
             * Tier
             * @default stated
             */
            tier: string;
            /**
             * Ttl
             * @default permanent
             */
            ttl: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Ok */
            ok: boolean;
            chain: components["schemas"]["ChainState"];
            /**
             * Demo Loaded
             * @default false
             */
            demo_loaded: boolean;
        };
        /** ImportIn */
        ImportIn: {
            /** Text */
            text: string;
        };
        /** ImportOut */
        ImportOut: {
            /** Kept */
            kept: number;
            /** Undated */
            undated: number;
            /** Questions */
            questions: components["schemas"]["LooseEndOut"][];
        };
        /** LooseEndIn */
        LooseEndIn: {
            /**
             * Action
             * @enum {string}
             */
            action: "added" | "dismissed";
        };
        /** LooseEndOut */
        LooseEndOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Mentions
             * @default 0
             */
            mentions: number;
            /**
             * At
             * @default
             */
            at: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /** OverviewOut */
        OverviewOut: {
            /** Entries Kept */
            entries_kept: number;
            /** People Mapped */
            people_mapped: number;
            /** Truths Revisited */
            truths_revisited: number;
            /** Returns After Quiet */
            returns_after_quiet: number;
            /** Days Written */
            days_written: number;
        };
        /** PersonaIn */
        PersonaIn: {
            /** Name */
            name: string;
            /**
             * Alias
             * @default
             */
            alias: string;
            /**
             * Kind
             * @default
             */
            kind: string;
            /**
             * Thought Then
             * @default
             */
            thought_then: string;
            /**
             * Think Now
             * @default
             */
            think_now: string;
            /**
             * Still Relevant
             * @default true
             */
            still_relevant: boolean;
        };
        /** PersonaOut */
        PersonaOut: {
            /** Id */
            id: string;
            /**
             * At
             * @default
             */
            at: string;
            /** Name */
            name: string;
            /**
             * Alias
             * @default
             */
            alias: string;
            /**
             * Kind
             * @default
             */
            kind: string;
            /**
             * Thought Then
             * @default
             */
            thought_then: string;
            /**
             * Think Now
             * @default
             */
            think_now: string;
            /**
             * Still Relevant
             * @default true
             */
            still_relevant: boolean;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
            /**
             * Mentions
             * @default 0
             */
            mentions: number;
            /**
             * Last Line
             * @default
             */
            last_line: string;
        };
        /**
         * ReflectionSettings
         * @description Everything the reflection loop is allowed to do, and its default answer.
         *
         *     questions_on is FALSE by default and only the user may change it (ADR 003).
         */
        ReflectionSettings: {
            /**
             * Questions On
             * @default false
             */
            questions_on: boolean;
            /**
             * Matching
             * @default shared words only
             * @enum {string}
             */
            matching: "meaning" | "shared words only";
            /**
             * Model Present
             * @default false
             */
            model_present: boolean;
            /**
             * Indexed
             * @default 0
             */
            indexed: number;
        };
        /** ReflectionSettingsIn */
        ReflectionSettingsIn: {
            /** Questions On */
            questions_on: boolean;
        };
        /**
         * RelatedEntry
         * @description A past entry offered beside the one in front of you.
         *
         *     `entry` is the user's own record, verbatim from the ledger. There is no
         *     field here for a summary, a theme, a label or a reason, and there must
         *     never be one: ADR 003 puts the user's words on screen or nothing.
         */
        RelatedEntry: {
            entry: components["schemas"]["EntryOut"];
            /** Score */
            score: number;
        };
        /** RelatedOut */
        RelatedOut: {
            /**
             * Related
             * @default []
             */
            related: components["schemas"]["RelatedEntry"][];
            /**
             * Matching
             * @default shared words only
             * @enum {string}
             */
            matching: "meaning" | "shared words only";
        };
        /** RelatedTextIn */
        RelatedTextIn: {
            /** Text */
            text: string;
        };
        /** SaveOut */
        SaveOut: {
            /** Saved */
            saved: boolean;
            /**
             * Needs Choice
             * @default false
             */
            needs_choice: boolean;
            /**
             * Found
             * @default []
             */
            found: string[];
            entry?: components["schemas"]["EntryOut"] | null;
            chain?: components["schemas"]["ChainState"] | null;
        };
        /** ThreadOut */
        ThreadOut: {
            persona: components["schemas"]["PersonaOut"];
            /** Entries */
            entries: components["schemas"]["EntryOut"][];
            /** Truths */
            truths: components["schemas"]["TruthOut"][];
        };
        /** TimelineRow */
        TimelineRow: {
            /** At */
            at: string;
            /** Kind */
            kind: string;
            /** Id */
            id: string;
            /**
             * Headline
             * @default
             */
            headline: string;
            /**
             * Feeling
             * @default
             */
            feeling: string;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /** TruthIn */
        TruthIn: {
            /**
             * About
             * @default self
             */
            about: string;
            /** Text */
            text: string;
            /**
             * Share Draft
             * @default
             */
            share_draft: string;
            /** Supersedes */
            supersedes?: string | null;
        };
        /** TruthOut */
        TruthOut: {
            /** Id */
            id: string;
            /**
             * About
             * @default self
             */
            about: string;
            /**
             * About Name
             * @default Yourself
             */
            about_name: string;
            /** Text */
            text: string;
            /**
             * Share Draft
             * @default
             */
            share_draft: string;
            /**
             * Valid From
             * @default
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Current
             * @default true
             */
            current: boolean;
            /** Supersedes */
            supersedes?: string | null;
            /**
             * Demo
             * @default false
             */
            demo: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WipeOut */
        WipeOut: {
            /** Removed */
            removed: number;
        };
        /** YouOut */
        YouOut: {
            overview: components["schemas"]["OverviewOut"];
            /** Timeline */
            timeline: components["schemas"]["TimelineRow"][];
            /** Written Days */
            written_days: string[];
            /** Truth Days */
            truth_days: string[];
            /** Year Ago */
            year_ago: components["schemas"]["EntryOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_entries_api_entries_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_api_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_personas_api_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"][];
                };
            };
        };
    };
    create_persona_api_personas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_persona_api_personas__persona_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_thread_api_personas__persona_id__thread_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_truths_api_truths_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruthOut"][];
                };
            };
        };
    };
    create_truth_api_truths_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TruthIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_loose_ends_api_loose_ends_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LooseEndOut"][];
                };
            };
        };
    };
    answer_loose_end_api_loose_ends__loose_end_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loose_end_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LooseEndIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LooseEndOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_text_api_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    you_api_you_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YouOut"];
                };
            };
        };
    };
    reflection_settings_api_reflection_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionSettings"];
                };
            };
        };
    };
    set_reflection_settings_api_reflection_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReflectionSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    related_to_draft_api_reflection_related_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelatedTextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    related_entries_api_reflection_related__entry_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_everything_api_export_get: {
        parameters: {
            query?: {
                include_demo?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_demo_api_demo_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    wipe_demo_api_demo_wipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WipeOut"];
                };
            };
        };
    };
}
